RUTINA_RECTO = 0
RUTINA_DIAGONAL = 1
RUTINA_DIAGONAL_DERECHA = 2
RUTINA_DIAGONAL_IZQUIERDA = 3

#MOVIMIENTOS
MOVE_NONE = -1
MOVE_RECT = 0
MOVE_LEFT = 1
MOVE_RIGHT = 2
MOVE_UP = 3
MOVE_UP_LEFT = 4
MOVE_UP_RIGHT = 5
MOVE_DOWN = 6
MOVE_DOWN_LEFT = 7
MOVE_DOWN_RIGHT = 8